# Generated by Django 3.1 on 2021-01-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projektrouska', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='precaution',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='precaution',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
