# Generated by Django 3.1 on 2020-12-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektrouska', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precaution',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
