# Generated by Django 3.1 on 2021-01-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projektrouska', '0002_auto_20210104_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precaution',
            name='priority',
            field=models.IntegerField(choices=[(-1, 'Not filled'),
                                               (0, 'Redundant (it is here just for auto-check)'),
                                               (1, 'It might be useful'),
                                               (10, 'Slightly important information, good to know'),
                                               (100, 'Important information, have to know'),
                                               (1000, 'Extremely important')], default=-1),
        ),
    ]
