# Generated by Django 3.1 on 2020-12-14 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektrouska', '0002_auto_20201214_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='external_contents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projektrouska.externalcontent'),
        ),
    ]
