# Generated by Django 3.1 on 2020-12-14 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektrouska', '0003_auto_20201214_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='cathegory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projektrouska.cathegory'),
        ),
        migrations.AlterField(
            model_name='pes_history',
            name='pes_general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektrouska.pes_general'),
        ),
    ]
