# Generated by Django 3.1 on 2021-01-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projektrouska', '0003_auto_20210104_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcontent',
            name='url_external',
            field=models.TextField(),
        ),
    ]
