# Generated by Django 3.1 on 2021-01-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('projektrouska', '0004_auto_20210104_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuts4',
            name='district',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='projektrouska.district'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('id', 'region', 'state')},
        ),
        migrations.RemoveField(
            model_name='district',
            name='nuts4',
        ),
    ]
