# Generated by Django 3.1 on 2020-12-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektrouska', '0004_auto_20201214_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcontent',
            name='img_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
