# Generated by Django 3.1 on 2020-12-14 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektrouska', '0005_auto_20201214_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcontent',
            name='date_inserted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
