# Generated by Django 3.1 on 2020-12-26 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projektrouska', '0006_auto_20201214_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 26, 21, 40, 17, 149489)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parts',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='precaution',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 26, 21, 40, 37, 644477)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='precaution',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
