# Generated by Django 3.1 on 2020-12-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projektrouska', '0007_auto_20201226_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precaution',
            name='status',
            field=models.IntegerField(
                choices=[(1, 'Active (auto)'), (0, 'Disabled (auto)'), (3, 'Active (force)'), (-1, 'Disabled (force)'),
                         (2, 'Active (check required)'), (-2, 'Disabled (maintenance in progress)')], default=1),
        ),
    ]
