insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (1, 2, 'Okres Benešov', 2);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (1, 2, 'Okres Benešov', 26);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (1, 2, 'Okres Benešov', 27);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (2, 2, 'Okres Beroun', 3);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (2, 2, 'Okres Beroun', 9);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (3, 11, 'Okres Blansko', 138);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (3, 11, 'Okres Blansko', 139);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (4, 11, 'Okres Břeclav', 141);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (4, 11, 'Okres Břeclav', 144);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (4, 11, 'Okres Břeclav', 148);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (5, 11, 'Okres Brno-město', 140);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (6, 11, 'Okres Brno-venkov', 145);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (6, 11, 'Okres Brno-venkov', 146);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (6, 11, 'Okres Brno-venkov', 150);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (6, 11, 'Okres Brno-venkov', 151);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (6, 11, 'Okres Brno-venkov', 153);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (6, 11, 'Okres Brno-venkov', 154);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (6, 11, 'Okres Brno-venkov', 158);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (7, 14, 'Okres Bruntál', 187);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (7, 14, 'Okres Bruntál', 198);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (7, 14, 'Okres Bruntál', 204);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (8, 7, 'Okres Česká Lípa', 83);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (8, 7, 'Okres Česká Lípa', 88);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (9, 3, 'Okres České Budějovice', 29);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (9, 3, 'Okres České Budějovice', 40);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (9, 3, 'Okres České Budějovice', 42);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (10, 3, 'Okres Český Krumlov', 30);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (10, 3, 'Okres Český Krumlov', 33);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (11, 5, 'Okres Cheb', 60);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (11, 5, 'Okres Cheb', 61);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (11, 5, 'Okres Cheb', 64);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (12, 6, 'Okres Chomutov', 69);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (12, 6, 'Okres Chomutov', 70);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (13, 9, 'Okres Chrudim', 109);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (13, 9, 'Okres Chrudim', 111);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (14, 6, 'Okres Děčín', 68);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (14, 6, 'Okres Děčín', 78);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (14, 6, 'Okres Děčín', 81);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (15, 4, 'Okres Domažlice', 46);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (15, 4, 'Okres Domažlice', 48);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (16, 14, 'Okres Frýdek-Místek', 190);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (16, 14, 'Okres Frýdek-Místek', 191);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (16, 14, 'Okres Frýdek-Místek', 194);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (16, 14, 'Okres Frýdek-Místek', 205);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (17, 10, 'Okres Havlíčkův Brod', 124);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (17, 10, 'Okres Havlíčkův Brod', 126);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (17, 10, 'Okres Havlíčkův Brod', 133);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (18, 11, 'Okres Hodonín', 143);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (18, 11, 'Okres Hodonín', 147);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (18, 11, 'Okres Hodonín', 155);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (19, 8, 'Okres Hradec Králové', 97);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (19, 8, 'Okres Hradec Králové', 104);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (20, 7, 'Okres Jablonec nad Nisou', 85);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (20, 7, 'Okres Jablonec nad Nisou', 90);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (20, 7, 'Okres Jablonec nad Nisou', 92);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (21, 12, 'Okres Jeseník', 160);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (22, 8, 'Okres Jičín', 96);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (22, 8, 'Okres Jičín', 99);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (22, 8, 'Okres Jičín', 102);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (23, 10, 'Okres Jihlava', 127);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (23, 10, 'Okres Jihlava', 134);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (24, 3, 'Okres Jindřichův Hradec', 31);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (24, 3, 'Okres Jindřichův Hradec', 32);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (24, 3, 'Okres Jindřichův Hradec', 41);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (25, 5, 'Okres Karlovy Vary', 62);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (25, 5, 'Okres Karlovy Vary', 65);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (26, 14, 'Okres Karviná', 186);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (26, 14, 'Okres Karviná', 188);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (26, 14, 'Okres Karviná', 192);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (26, 14, 'Okres Karviná', 195);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (26, 14, 'Okres Karviná', 202);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (27, 2, 'Okres Kladno', 10);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (27, 2, 'Okres Kladno', 25);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (28, 4, 'Okres Klatovy', 47);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (28, 4, 'Okres Klatovy', 49);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (28, 4, 'Okres Klatovy', 58);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (29, 2, 'Okres Kolín', 7);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (29, 2, 'Okres Kolín', 11);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (30, 13, 'Okres Kroměříž', 172);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (30, 13, 'Okres Kroměříž', 173);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (30, 13, 'Okres Kroměříž', 174);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (31, 2, 'Okres Kutná Hora', 5);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (31, 2, 'Okres Kutná Hora', 13);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (32, 7, 'Okres Liberec', 84);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (32, 7, 'Okres Liberec', 87);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (33, 6, 'Okres Litoměřice', 71);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (33, 6, 'Okres Litoměřice', 74);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (33, 6, 'Okres Litoměřice', 77);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (34, 6, 'Okres Louny', 73);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (34, 6, 'Okres Louny', 76);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (34, 6, 'Okres Louny', 82);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (35, 2, 'Okres Mělník', 12);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (35, 2, 'Okres Mělník', 15);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (35, 2, 'Okres Mělník', 18);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (36, 2, 'Okres Mladá Boleslav', 16);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (36, 2, 'Okres Mladá Boleslav', 17);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (37, 6, 'Okres Most', 72);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (37, 6, 'Okres Most', 75);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (38, 8, 'Okres Náchod', 93);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (38, 8, 'Okres Náchod', 98);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (38, 8, 'Okres Náchod', 101);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (38, 8, 'Okres Náchod', 103);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (39, 14, 'Okres Nový Jičín', 185);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (39, 14, 'Okres Nový Jičín', 189);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (39, 14, 'Okres Nový Jičín', 196);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (39, 14, 'Okres Nový Jičín', 199);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (39, 14, 'Okres Nový Jičín', 200);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (40, 2, 'Okres Nymburk', 14);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (40, 2, 'Okres Nymburk', 19);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (40, 2, 'Okres Nymburk', 20);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (41, 12, 'Okres Olomouc', 163);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (41, 12, 'Okres Olomouc', 165);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (41, 12, 'Okres Olomouc', 168);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (41, 12, 'Okres Olomouc', 170);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (42, 14, 'Okres Opava', 193);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (42, 14, 'Okres Opava', 197);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (42, 14, 'Okres Opava', 201);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (42, 14, 'Okres Opava', 206);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (43, 14, 'Okres Ostrava-město', 203);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (44, 9, 'Okres Pardubice', 110);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (44, 9, 'Okres Pardubice', 116);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (44, 9, 'Okres Pardubice', 118);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (45, 10, 'Okres Pelhřimov', 125);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (45, 10, 'Okres Pelhřimov', 131);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (45, 10, 'Okres Pelhřimov', 132);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (46, 3, 'Okres Písek', 34);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (46, 3, 'Okres Písek', 35);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (47, 4, 'Okres Plzeň-jih', 45);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (47, 4, 'Okres Plzeň-jih', 51);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (47, 4, 'Okres Plzeň-jih', 54);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (47, 4, 'Okres Plzeň-jih', 56);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (48, 4, 'Okres Plzeň-město', 53);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (49, 4, 'Okres Plzeň-sever', 50);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (49, 4, 'Okres Plzeň-sever', 52);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (50, 3, 'Okres Prachatice', 36);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (50, 3, 'Okres Prachatice', 43);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (51, 2, 'Okres Praha-východ', 4);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (51, 2, 'Okres Praha-východ', 23);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (52, 2, 'Okres Praha-západ', 6);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (53, 12, 'Okres Přerov', 159);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (53, 12, 'Okres Přerov', 162);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (53, 12, 'Okres Přerov', 167);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (54, 2, 'Okres Příbram', 8);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (54, 2, 'Okres Příbram', 21);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (54, 2, 'Okres Příbram', 24);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (55, 12, 'Okres Prostějov', 161);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (55, 12, 'Okres Prostějov', 166);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (56, 2, 'Okres Rakovník', 22);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (57, 4, 'Okres Rokycany', 55);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (58, 8, 'Okres Rychnov nad Kněžnou', 94);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (58, 8, 'Okres Rychnov nad Kněžnou', 100);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (58, 8, 'Okres Rychnov nad Kněžnou', 105);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (59, 7, 'Okres Semily', 86);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (59, 7, 'Okres Semily', 89);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (59, 7, 'Okres Semily', 91);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (60, 5, 'Okres Sokolov', 63);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (60, 5, 'Okres Sokolov', 66);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (61, 3, 'Okres Strakonice', 28);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (61, 3, 'Okres Strakonice', 38);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (61, 3, 'Okres Strakonice', 44);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (62, 12, 'Okres Šumperk', 164);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (62, 12, 'Okres Šumperk', 169);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (62, 12, 'Okres Šumperk', 171);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (63, 9, 'Okres Svitavy', 114);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (63, 9, 'Okres Svitavy', 115);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (63, 9, 'Okres Svitavy', 117);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (63, 9, 'Okres Svitavy', 119);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (64, 3, 'Okres Tábor', 37);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (64, 3, 'Okres Tábor', 39);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (65, 4, 'Okres Tachov', 57);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (65, 4, 'Okres Tachov', 59);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (66, 6, 'Okres Teplice', 67);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (66, 6, 'Okres Teplice', 79);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (67, 10, 'Okres Třebíč', 128);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (67, 10, 'Okres Třebíč', 129);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (67, 10, 'Okres Třebíč', 135);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (68, 8, 'Okres Trutnov', 95);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (68, 8, 'Okres Trutnov', 106);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (68, 8, 'Okres Trutnov', 107);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (69, 13, 'Okres Uherské Hradiště', 178);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (69, 13, 'Okres Uherské Hradiště', 179);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (70, 6, 'Okres Ústí nad Labem', 80);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (71, 9, 'Okres Ústí nad Orlicí', 108);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (71, 9, 'Okres Ústí nad Orlicí', 112);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (71, 9, 'Okres Ústí nad Orlicí', 113);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (71, 9, 'Okres Ústí nad Orlicí', 120);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (71, 9, 'Okres Ústí nad Orlicí', 121);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (71, 9, 'Okres Ústí nad Orlicí', 122);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (72, 13, 'Okres Vsetín', 177);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (72, 13, 'Okres Vsetín', 181);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (72, 13, 'Okres Vsetín', 183);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (73, 11, 'Okres Vyškov', 142);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (73, 11, 'Okres Vyškov', 152);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (73, 11, 'Okres Vyškov', 156);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (74, 10, 'Okres Žďár nad Sázavou', 123);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (74, 10, 'Okres Žďár nad Sázavou', 130);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (74, 10, 'Okres Žďár nad Sázavou', 136);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (74, 10, 'Okres Žďár nad Sázavou', 137);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (75, 13, 'Okres Zlín', 175);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (75, 13, 'Okres Zlín', 176);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (75, 13, 'Okres Zlín', 180);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (75, 13, 'Okres Zlín', 182);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (75, 13, 'Okres Zlín', 184);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (76, 11, 'Okres Znojmo', 149);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (76, 11, 'Okres Znojmo', 157);
insert into DOSTATO6.OKRES (ID_OKRES, KRAJ_ID_KRAJ, NAZEV_OKRES, NUTS3_ID_NUTS) values (77, 1, 'Praha', 1);
