insert into DOSTATO6.OP_OM (OPATRENI_ID_OPATRENI, OBECMESTO_ID_OBECMESTO) values (8, 5791);
insert into DOSTATO6.OP_OM (OPATRENI_ID_OPATRENI, OBECMESTO_ID_OBECMESTO) values (40, 6474);
insert into DOSTATO6.OP_OM (OPATRENI_ID_OPATRENI, OBECMESTO_ID_OBECMESTO) values (41, 208);
