insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (44, 'Vodňany', 3117, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (45, 'Blovice', 3201, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (46, 'Domažlice', 3202, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (47, 'Horažďovice', 3203, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (48, 'Horšovský Týn', 3204, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (49, 'Klatovy', 3205, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (50, 'Kralovice', 3206, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (51, 'Nepomuk', 3207, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (52, 'Nýřany', 3208, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (53, 'Plzeň', 3209, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (54, 'Přeštice', 3210, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (55, 'Rokycany', 3211, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (56, 'Stod', 3212, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (57, 'Stříbro', 3213, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (58, 'Sušice', 3214, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (59, 'Tachov', 3215, 4);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (60, 'Aš', 4101, 5);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (61, 'Cheb', 4102, 5);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (62, 'Karlovy Vary', 4103, 5);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (63, 'Kraslice', 4104, 5);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (64, 'Mariánské Lázně', 4105, 5);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (65, 'Ostrov', 4106, 5);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (66, 'Sokolov', 4107, 5);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (67, 'Bílina', 4201, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (68, 'Děčín', 4202, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (69, 'Chomutov', 4203, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (70, 'Kadaň', 4204, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (71, 'Litoměřice', 4205, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (72, 'Litvínov', 4206, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (73, 'Louny', 4207, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (74, 'Lovosice', 4208, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (75, 'Most', 4209, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (76, 'Podbořany', 4210, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (77, 'Roudnice nad Labem', 4211, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (78, 'Rumburk', 4212, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (79, 'Teplice', 4213, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (80, 'Ústí nad Labem', 4214, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (81, 'Varnsdorf', 4215, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (82, 'Žatec', 4216, 6);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (83, 'Česká Lípa', 5101, 7);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (84, 'Frýdlant', 5102, 7);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (85, 'Jablonec nad Nisou', 5103, 7);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (86, 'Jilemnice', 5104, 7);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (87, 'Liberec', 5105, 7);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (88, 'Nový Bor', 5106, 7);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (89, 'Semily', 5107, 7);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (90, 'Tanvald', 5108, 7);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (91, 'Turnov', 5109, 7);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (92, 'Železný Brod', 5110, 7);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (93, 'Broumov', 5201, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (94, 'Dobruška', 5202, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (95, 'Dvůr Králové nad Labem', 5203, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (96, 'Hořice', 5204, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (97, 'Hradec Králové', 5205, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (98, 'Jaroměř', 5206, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (99, 'Jičín', 5207, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (100, 'Kostelec nad Orlicí', 5208, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (101, 'Náchod', 5209, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (102, 'Nová Paka', 5210, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (103, 'Nové Město nad Metují', 5211, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (104, 'Nový Bydžov', 5212, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (105, 'Rychnov nad Kněžnou', 5213, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (106, 'Trutnov', 5214, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (107, 'Vrchlabí', 5215, 8);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (108, 'Česká Třebová', 5301, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (109, 'Hlinsko', 5302, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (110, 'Holice', 5303, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (111, 'Chrudim', 5304, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (112, 'Králíky', 5305, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (113, 'Lanškroun', 5306, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (114, 'Litomyšl', 5307, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (115, 'Moravská Třebová', 5308, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (116, 'Pardubice', 5309, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (117, 'Polička', 5310, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (118, 'Přelouč', 5311, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (119, 'Svitavy', 5312, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (120, 'Ústí nad Orlicí', 5313, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (121, 'Vysoké Mýto', 5314, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (122, 'Žamberk', 5315, 9);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (123, 'Bystřice nad Pernštejnem', 6101, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (124, 'Havlíčkův Brod', 6102, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (125, 'Humpolec', 6103, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (126, 'Chotěboř', 6104, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (127, 'Jihlava', 6105, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (128, 'Moravské Budějovice', 6106, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (129, 'Náměšť nad Oslavou', 6107, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (130, 'Nové Město na Moravě', 6108, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (131, 'Pacov', 6109, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (132, 'Pelhřimov', 6110, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (133, 'Světlá nad Sázavou', 6111, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (134, 'Telč', 6112, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (135, 'Třebíč', 6113, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (136, 'Velké Meziříčí', 6114, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (137, 'Žďár nad Sázavou', 6115, 10);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (138, 'Blansko', 6201, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (139, 'Boskovice', 6202, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (140, 'Brno', 6203, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (141, 'Břeclav', 6204, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (142, 'Bučovice', 6205, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (143, 'Hodonín', 6206, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (144, 'Hustopeče', 6207, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (145, 'Ivančice', 6208, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (146, 'Kuřim', 6209, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (147, 'Kyjov', 6210, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (148, 'Mikulov', 6211, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (149, 'Moravský Krumlov', 6212, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (150, 'Pohořelice', 6213, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (151, 'Rosice', 6214, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (152, 'Slavkov u Brna', 6215, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (153, 'Šlapanice', 6216, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (154, 'Tišnov', 6217, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (155, 'Veselí nad Moravou', 6218, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (156, 'Vyškov', 6219, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (157, 'Znojmo', 6220, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (158, 'Židlochovice', 6221, 11);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (159, 'Hranice', 7101, 12);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (160, 'Jeseník', 7102, 12);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (161, 'Konice', 7103, 12);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (162, 'Lipník nad Bečvou', 7104, 12);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (163, 'Litovel', 7105, 12);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (164, 'Mohelnice', 7106, 12);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (165, 'Olomouc', 7107, 12);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (166, 'Prostějov', 7108, 12);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (167, 'Přerov', 7109, 12);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (168, 'Šternberk', 7110, 12);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (169, 'Šumperk', 7111, 12);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (170, 'Uničov', 7112, 12);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (171, 'Zábřeh', 7113, 12);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (172, 'Bystřice pod Hostýnem', 7201, 13);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (173, 'Holešov', 7202, 13);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (174, 'Kroměříž', 7203, 13);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (175, 'Luhačovice', 7204, 13);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (176, 'Otrokovice', 7205, 13);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (177, 'Rožnov pod Radhoštěm', 7206, 13);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (178, 'Uherské Hradiště', 7207, 13);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (179, 'Uherský Brod', 7208, 13);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (180, 'Valašské Klobouky', 7209, 13);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (181, 'Valašské Meziříčí', 7210, 13);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (182, 'Vizovice', 7211, 13);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (183, 'Vsetín', 7212, 13);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (184, 'Zlín', 7213, 13);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (185, 'Bílovec', 8101, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (186, 'Bohumín', 8102, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (187, 'Bruntál', 8103, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (188, 'Český Těšín', 8104, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (189, 'Frenštát pod Radhoštěm', 8105, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (190, 'Frýdek-Místek', 8106, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (191, 'Frýdlant nad Ostravicí', 8107, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (192, 'Havířov', 8108, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (193, 'Hlučín', 8109, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (194, 'Jablunkov', 8110, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (195, 'Karviná', 8111, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (196, 'Kopřivnice', 8112, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (197, 'Kravaře', 8113, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (198, 'Krnov', 8114, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (199, 'Nový Jičín', 8115, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (200, 'Odry', 8116, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (201, 'Opava', 8117, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (202, 'Orlová', 8118, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (203, 'Ostrava', 8119, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (204, 'Rýmařov', 8120, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (205, 'Třinec', 8121, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (206, 'Vítkov', 8122, 14);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (1, 'Praha', 1000, 1);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (2, 'Benešov', 2101, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (3, 'Beroun', 2102, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (4, 'Brandýs nad Labem-Stará Boleslav', 2103, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (5, 'Čáslav', 2104, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (6, 'Černošice', 2105, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (7, 'Český Brod', 2106, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (8, 'Dobříš', 2107, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (9, 'Hořovice', 2108, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (10, 'Kladno', 2109, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (11, 'Kolín', 2110, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (12, 'Kralupy nad Vltavou', 2111, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (13, 'Kutná Hora', 2112, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (14, 'Lysá nad Labem', 2113, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (15, 'Mělník', 2114, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (16, 'Mladá Boleslav', 2115, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (17, 'Mnichovo Hradiště', 2116, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (18, 'Neratovice', 2117, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (19, 'Nymburk', 2118, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (20, 'Poděbrady', 2119, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (21, 'Příbram', 2120, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (22, 'Rakovník', 2121, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (23, 'Říčany', 2122, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (24, 'Sedlčany', 2123, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (25, 'Slaný', 2124, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (26, 'Vlašim', 2125, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (27, 'Votice', 2126, 2);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (28, 'Blatná', 3101, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (29, 'České Budějovice', 3102, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (30, 'Český Krumlov', 3103, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (31, 'Dačice', 3104, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (32, 'Jindřichův Hradec', 3105, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (33, 'Kaplice', 3106, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (34, 'Milevsko', 3107, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (35, 'Písek', 3108, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (36, 'Prachatice', 3109, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (37, 'Soběslav', 3110, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (38, 'Strakonice', 3111, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (39, 'Tábor', 3112, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (40, 'Trhové Sviny', 3113, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (41, 'Třeboň', 3114, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (42, 'Týn nad Vltavou', 3115, 3);
insert into DOSTATO6.NUTS3 (ID_NUTS, NAZEV_NUTS, KOD_NUTS, KRAJ_ID_KRAJ) values (43, 'Vimperk', 3116, 3);
