INSERT INTO DOSTATO6.OP_OM (OPATRENI_ID_OPATRENI, OBECMESTO_ID_OBECMESTO) VALUES (8, 5791);
INSERT INTO DOSTATO6.OP_OM (OPATRENI_ID_OPATRENI, OBECMESTO_ID_OBECMESTO) VALUES (40, 6474);
INSERT INTO DOSTATO6.OP_OM (OPATRENI_ID_OPATRENI, OBECMESTO_ID_OBECMESTO) VALUES (41, 208);