INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (1, 'Praha', 'NULL', 77, 1, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (2, 'Okres Benešov', 'NULL', 1, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (3, 'Okres Beroun', 'NULL', 2, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (4, 'Okres Praha-východ', 'NULL', 51, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (5, 'Okres Kutná Hora', 'NULL', 31, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (6, 'Okres Praha-západ', 'NULL', 52, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (7, 'Okres Kolín', 'NULL', 29, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (8, 'Okres Příbram', 'NULL', 54, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (9, 'Okres Beroun', 'NULL', 2, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (10, 'Okres Kladno', 'NULL', 27, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (11, 'Okres Kolín', 'NULL', 29, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (12, 'Okres Mělník', 'NULL', 35, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (13, 'Okres Kutná Hora', 'NULL', 31, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (14, 'Okres Nymburk', 'NULL', 40, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (15, 'Okres Mělník', 'NULL', 35, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (16, 'Okres Mladá Boleslav', 'NULL', 36, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (17, 'Okres Mladá Boleslav', 'NULL', 36, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (18, 'Okres Mělník', 'NULL', 35, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (19, 'Okres Nymburk', 'NULL', 40, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (20, 'Okres Nymburk', 'NULL', 40, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (21, 'Okres Příbram', 'NULL', 54, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (22, 'Okres Rakovník', 'NULL', 56, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (23, 'Okres Praha-východ', 'NULL', 51, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (24, 'Okres Příbram', 'NULL', 54, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (25, 'Okres Kladno', 'NULL', 27, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (26, 'Okres Benešov', 'NULL', 1, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (27, 'Okres Benešov', 'NULL', 1, 2, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (28, 'Okres Strakonice', 'NULL', 61, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (29, 'Okres České Budějovice', 'NULL', 9, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (30, 'Okres Český Krumlov', 'NULL', 10, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (31, 'Okres Jindřichův Hradec', 'NULL', 24, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (32, 'Okres Jindřichův Hradec', 'NULL', 24, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (33, 'Okres Český Krumlov', 'NULL', 10, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (34, 'Okres Písek', 'NULL', 46, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (35, 'Okres Písek', 'NULL', 46, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (36, 'Okres Prachatice', 'NULL', 50, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (37, 'Okres Tábor', 'NULL', 64, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (38, 'Okres Strakonice', 'NULL', 61, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (39, 'Okres Tábor', 'NULL', 64, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (40, 'Okres České Budějovice', 'NULL', 9, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (41, 'Okres Jindřichův Hradec', 'NULL', 24, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (42, 'Okres České Budějovice', 'NULL', 9, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (43, 'Okres Prachatice', 'NULL', 50, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (44, 'Okres Strakonice', 'NULL', 61, 3, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (45, 'Okres Plzeň-jih', 'NULL', 47, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (46, 'Okres Domažlice', 'NULL', 15, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (47, 'Okres Klatovy', 'NULL', 28, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (48, 'Okres Domažlice', 'NULL', 15, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (49, 'Okres Klatovy', 'NULL', 28, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (50, 'Okres Plzeň-sever', 'NULL', 49, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (51, 'Okres Plzeň-jih', 'NULL', 47, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (52, 'Okres Plzeň-sever', 'NULL', 49, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (53, 'Okres Plzeň-město', 'NULL', 48, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (54, 'Okres Plzeň-jih', 'NULL', 47, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (55, 'Okres Rokycany', 'NULL', 57, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (56, 'Okres Plzeň-jih', 'NULL', 47, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (57, 'Okres Tachov', 'NULL', 65, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (58, 'Okres Klatovy', 'NULL', 28, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (59, 'Okres Tachov', 'NULL', 65, 4, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (60, 'Okres Cheb', 'NULL', 11, 5, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (61, 'Okres Cheb', 'NULL', 11, 5, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (62, 'Okres Karlovy Vary', 'NULL', 25, 5, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (63, 'Okres Sokolov', 'NULL', 60, 5, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (64, 'Okres Cheb', 'NULL', 11, 5, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (65, 'Okres Karlovy Vary', 'NULL', 25, 5, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (66, 'Okres Sokolov', 'NULL', 60, 5, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (67, 'Okres Teplice', 'NULL', 66, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (68, 'Okres Děčín', 'NULL', 14, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (69, 'Okres Chomutov', 'NULL', 12, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (70, 'Okres Chomutov', 'NULL', 12, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (71, 'Okres Litoměřice', 'NULL', 33, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (72, 'Okres Most', 'NULL', 37, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (73, 'Okres Louny', 'NULL', 34, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (74, 'Okres Litoměřice', 'NULL', 33, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (75, 'Okres Most', 'NULL', 37, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (76, 'Okres Louny', 'NULL', 34, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (77, 'Okres Litoměřice', 'NULL', 33, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (78, 'Okres Děčín', 'NULL', 14, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (79, 'Okres Teplice', 'NULL', 66, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (80, 'Okres Ústí nad Labem', 'NULL', 70, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (81, 'Okres Děčín', 'NULL', 14, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (82, 'Okres Louny', 'NULL', 34, 6, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (83, 'Okres Česká Lípa', 'NULL', 8, 7, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (84, 'Okres Liberec', 'NULL', 32, 7, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (85, 'Okres Jablonec nad Nisou', 'NULL', 20, 7, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (86, 'Okres Semily', 'NULL', 59, 7, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (87, 'Okres Liberec', 'NULL', 32, 7, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (88, 'Okres Česká Lípa', 'NULL', 8, 7, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (89, 'Okres Semily', 'NULL', 59, 7, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (90, 'Okres Jablonec nad Nisou', 'NULL', 20, 7, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (91, 'Okres Semily', 'NULL', 59, 7, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (92, 'Okres Jablonec nad Nisou', 'NULL', 20, 7, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (93, 'Okres Náchod', 'NULL', 38, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (94, 'Okres Rychnov nad Kněžnou', 'NULL', 58, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (95, 'Okres Trutnov', 'NULL', 68, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (96, 'Okres Jičín', 'NULL', 22, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (97, 'Okres Hradec Králové', 'NULL', 19, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (98, 'Okres Náchod', 'NULL', 38, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (99, 'Okres Jičín', 'NULL', 22, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (100, 'Okres Rychnov nad Kněžnou', 'NULL', 58, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (101, 'Okres Náchod', 'NULL', 38, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (102, 'Okres Jičín', 'NULL', 22, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (103, 'Okres Náchod', 'NULL', 38, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (104, 'Okres Hradec Králové', 'NULL', 19, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (105, 'Okres Rychnov nad Kněžnou', 'NULL', 58, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (106, 'Okres Trutnov', 'NULL', 68, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (107, 'Okres Trutnov', 'NULL', 68, 8, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (108, 'Okres Ústí nad Orlicí', 'NULL', 71, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (109, 'Okres Chrudim', 'NULL', 13, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (110, 'Okres Pardubice', 'NULL', 44, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (111, 'Okres Chrudim', 'NULL', 13, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (112, 'Okres Ústí nad Orlicí', 'NULL', 71, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (113, 'Okres Ústí nad Orlicí', 'NULL', 71, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (114, 'Okres Svitavy', 'NULL', 63, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (115, 'Okres Svitavy', 'NULL', 63, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (116, 'Okres Pardubice', 'NULL', 44, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (117, 'Okres Svitavy', 'NULL', 63, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (118, 'Okres Pardubice', 'NULL', 44, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (119, 'Okres Svitavy', 'NULL', 63, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (120, 'Okres Ústí nad Orlicí', 'NULL', 71, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (121, 'Okres Ústí nad Orlicí', 'NULL', 71, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (122, 'Okres Ústí nad Orlicí', 'NULL', 71, 9, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (123, 'Okres Žďár nad Sázavou', 'NULL', 74, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (124, 'Okres Havlíčkův Brod', 'NULL', 17, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (125, 'Okres Pelhřimov', 'NULL', 45, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (126, 'Okres Havlíčkův Brod', 'NULL', 17, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (127, 'Okres Jihlava', 'NULL', 23, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (128, 'Okres Třebíč', 'NULL', 67, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (129, 'Okres Třebíč', 'NULL', 67, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (130, 'Okres Žďár nad Sázavou', 'NULL', 74, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (131, 'Okres Pelhřimov', 'NULL', 45, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (132, 'Okres Pelhřimov', 'NULL', 45, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (133, 'Okres Havlíčkův Brod', 'NULL', 17, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (134, 'Okres Jihlava', 'NULL', 23, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (135, 'Okres Třebíč', 'NULL', 67, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (136, 'Okres Žďár nad Sázavou', 'NULL', 74, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (137, 'Okres Žďár nad Sázavou', 'NULL', 74, 10, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (138, 'Okres Blansko', 'NULL', 3, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (139, 'Okres Blansko', 'NULL', 3, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (140, 'Okres Brno-město', 'NULL', 5, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (141, 'Okres Břeclav', 'NULL', 4, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (142, 'Okres Vyškov', 'NULL', 73, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (143, 'Okres Hodonín', 'NULL', 18, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (144, 'Okres Břeclav', 'NULL', 4, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (145, 'Okres Brno-venkov', 'NULL', 6, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (146, 'Okres Brno-venkov', 'NULL', 6, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (147, 'Okres Hodonín', 'NULL', 18, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (148, 'Okres Břeclav', 'NULL', 4, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (149, 'Okres Znojmo', 'NULL', 76, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (150, 'Okres Brno-venkov', 'NULL', 6, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (151, 'Okres Brno-venkov', 'NULL', 6, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (152, 'Okres Vyškov', 'NULL', 73, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (153, 'Okres Brno-venkov', 'NULL', 6, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (154, 'Okres Brno-venkov', 'NULL', 6, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (155, 'Okres Hodonín', 'NULL', 18, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (156, 'Okres Vyškov', 'NULL', 73, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (157, 'Okres Znojmo', 'NULL', 76, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (158, 'Okres Brno-venkov', 'NULL', 6, 11, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (159, 'Okres Přerov', 'NULL', 53, 12, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (160, 'Okres Jeseník', 'NULL', 21, 12, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (161, 'Okres Prostějov', 'NULL', 55, 12, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (162, 'Okres Přerov', 'NULL', 53, 12, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (163, 'Okres Olomouc', 'NULL', 41, 12, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (164, 'Okres Šumperk', 'NULL', 62, 12, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (165, 'Okres Olomouc', 'NULL', 41, 12, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (166, 'Okres Prostějov', 'NULL', 55, 12, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (167, 'Okres Přerov', 'NULL', 53, 12, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (168, 'Okres Olomouc', 'NULL', 41, 12, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (169, 'Okres Šumperk', 'NULL', 62, 12, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (170, 'Okres Olomouc', 'NULL', 41, 12, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (171, 'Okres Šumperk', 'NULL', 62, 12, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (172, 'Okres Kroměříž', 'NULL', 30, 13, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (173, 'Okres Kroměříž', 'NULL', 30, 13, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (174, 'Okres Kroměříž', 'NULL', 30, 13, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (175, 'Okres Zlín', 'NULL', 75, 13, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (176, 'Okres Zlín', 'NULL', 75, 13, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (177, 'Okres Vsetín', 'NULL', 72, 13, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (178, 'Okres Uherské Hradiště', 'NULL', 69, 13, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (179, 'Okres Uherské Hradiště', 'NULL', 69, 13, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (180, 'Okres Zlín', 'NULL', 75, 13, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (181, 'Okres Vsetín', 'NULL', 72, 13, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (182, 'Okres Zlín', 'NULL', 75, 13, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (183, 'Okres Vsetín', 'NULL', 72, 13, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (184, 'Okres Zlín', 'NULL', 75, 13, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (185, 'Okres Nový Jičín', 'NULL', 39, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (186, 'Okres Karviná', 'NULL', 26, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (187, 'Okres Bruntál', 'NULL', 7, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (188, 'Okres Karviná', 'NULL', 26, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (189, 'Okres Nový Jičín', 'NULL', 39, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (190, 'Okres Frýdek-Místek', 'NULL', 16, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (191, 'Okres Frýdek-Místek', 'NULL', 16, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (192, 'Okres Karviná', 'NULL', 26, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (193, 'Okres Opava', 'NULL', 42, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (194, 'Okres Frýdek-Místek', 'NULL', 16, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (195, 'Okres Karviná', 'NULL', 26, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (196, 'Okres Nový Jičín', 'NULL', 39, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (197, 'Okres Opava', 'NULL', 42, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (198, 'Okres Bruntál', 'NULL', 7, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (199, 'Okres Nový Jičín', 'NULL', 39, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (200, 'Okres Nový Jičín', 'NULL', 39, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (201, 'Okres Opava', 'NULL', 42, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (202, 'Okres Karviná', 'NULL', 26, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (203, 'Okres Ostrava-město', 'NULL', 43, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (204, 'Okres Bruntál', 'NULL', 7, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (205, 'Okres Frýdek-Místek', 'NULL', 16, 14, 1);
INSERT INTO public.district (id, name, code, nuts4_id, region_id, state_id) VALUES (206, 'Okres Opava', 'NULL', 42, 14, 1);