INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (44, 'Vodňany', 3117, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (45, 'Blovice', 3201, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (46, 'Domažlice', 3202, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (47, 'Horažďovice', 3203, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (48, 'Horšovský Týn', 3204, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (49, 'Klatovy', 3205, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (50, 'Kralovice', 3206, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (51, 'Nepomuk', 3207, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (52, 'Nýřany', 3208, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (53, 'Plzeň', 3209, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (54, 'Přeštice', 3210, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (55, 'Rokycany', 3211, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (56, 'Stod', 3212, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (57, 'Stříbro', 3213, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (58, 'Sušice', 3214, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (59, 'Tachov', 3215, 'NULL', 4, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (60, 'Aš', 4101, 'NULL', 5, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (61, 'Cheb', 4102, 'NULL', 5, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (62, 'Karlovy Vary', 4103, 'NULL', 5, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (63, 'Kraslice', 4104, 'NULL', 5, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (64, 'Mariánské Lázně', 4105, 'NULL', 5, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (65, 'Ostrov', 4106, 'NULL', 5, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (66, 'Sokolov', 4107, 'NULL', 5, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (67, 'Bílina', 4201, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (68, 'Děčín', 4202, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (69, 'Chomutov', 4203, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (70, 'Kadaň', 4204, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (71, 'Litoměřice', 4205, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (72, 'Litvínov', 4206, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (73, 'Louny', 4207, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (74, 'Lovosice', 4208, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (75, 'Most', 4209, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (76, 'Podbořany', 4210, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (77, 'Roudnice nad Labem', 4211, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (78, 'Rumburk', 4212, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (79, 'Teplice', 4213, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (80, 'Ústí nad Labem', 4214, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (81, 'Varnsdorf', 4215, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (82, 'Žatec', 4216, 'NULL', 6, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (83, 'Česká Lípa', 5101, 'NULL', 7, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (84, 'Frýdlant', 5102, 'NULL', 7, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (85, 'Jablonec nad Nisou', 5103, 'NULL', 7, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (86, 'Jilemnice', 5104, 'NULL', 7, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (87, 'Liberec', 5105, 'NULL', 7, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (88, 'Nový Bor', 5106, 'NULL', 7, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (89, 'Semily', 5107, 'NULL', 7, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (90, 'Tanvald', 5108, 'NULL', 7, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (91, 'Turnov', 5109, 'NULL', 7, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (92, 'Železný Brod', 5110, 'NULL', 7, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (93, 'Broumov', 5201, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (94, 'Dobruška', 5202, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (95, 'Dvůr Králové nad Labem', 5203, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (96, 'Hořice', 5204, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (97, 'Hradec Králové', 5205, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (98, 'Jaroměř', 5206, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (99, 'Jičín', 5207, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (100, 'Kostelec nad Orlicí', 5208, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (101, 'Náchod', 5209, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (102, 'Nová Paka', 5210, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (103, 'Nové Město nad Metují', 5211, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (104, 'Nový Bydžov', 5212, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (105, 'Rychnov nad Kněžnou', 5213, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (106, 'Trutnov', 5214, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (107, 'Vrchlabí', 5215, 'NULL', 8, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (108, 'Česká Třebová', 5301, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (109, 'Hlinsko', 5302, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (110, 'Holice', 5303, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (111, 'Chrudim', 5304, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (112, 'Králíky', 5305, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (113, 'Lanškroun', 5306, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (114, 'Litomyšl', 5307, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (115, 'Moravská Třebová', 5308, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (116, 'Pardubice', 5309, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (117, 'Polička', 5310, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (118, 'Přelouč', 5311, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (119, 'Svitavy', 5312, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (120, 'Ústí nad Orlicí', 5313, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (121, 'Vysoké Mýto', 5314, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (122, 'Žamberk', 5315, 'NULL', 9, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (123, 'Bystřice nad Pernštejnem', 6101, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (124, 'Havlíčkův Brod', 6102, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (125, 'Humpolec', 6103, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (126, 'Chotěboř', 6104, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (127, 'Jihlava', 6105, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (128, 'Moravské Budějovice', 6106, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (129, 'Náměšť nad Oslavou', 6107, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (130, 'Nové Město na Moravě', 6108, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (131, 'Pacov', 6109, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (132, 'Pelhřimov', 6110, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (133, 'Světlá nad Sázavou', 6111, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (134, 'Telč', 6112, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (135, 'Třebíč', 6113, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (136, 'Velké Meziříčí', 6114, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (137, 'Žďár nad Sázavou', 6115, 'NULL', 10, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (138, 'Blansko', 6201, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (139, 'Boskovice', 6202, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (140, 'Brno', 6203, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (141, 'Břeclav', 6204, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (142, 'Bučovice', 6205, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (143, 'Hodonín', 6206, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (144, 'Hustopeče', 6207, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (145, 'Ivančice', 6208, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (146, 'Kuřim', 6209, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (147, 'Kyjov', 6210, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (148, 'Mikulov', 6211, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (149, 'Moravský Krumlov', 6212, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (150, 'Pohořelice', 6213, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (151, 'Rosice', 6214, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (152, 'Slavkov u Brna', 6215, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (153, 'Šlapanice', 6216, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (154, 'Tišnov', 6217, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (155, 'Veselí nad Moravou', 6218, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (156, 'Vyškov', 6219, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (157, 'Znojmo', 6220, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (158, 'Židlochovice', 6221, 'NULL', 11, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (159, 'Hranice', 7101, 'NULL', 12, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (160, 'Jeseník', 7102, 'NULL', 12, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (161, 'Konice', 7103, 'NULL', 12, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (162, 'Lipník nad Bečvou', 7104, 'NULL', 12, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (163, 'Litovel', 7105, 'NULL', 12, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (164, 'Mohelnice', 7106, 'NULL', 12, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (165, 'Olomouc', 7107, 'NULL', 12, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (166, 'Prostějov', 7108, 'NULL', 12, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (167, 'Přerov', 7109, 'NULL', 12, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (168, 'Šternberk', 7110, 'NULL', 12, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (169, 'Šumperk', 7111, 'NULL', 12, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (170, 'Uničov', 7112, 'NULL', 12, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (171, 'Zábřeh', 7113, 'NULL', 12, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (172, 'Bystřice pod Hostýnem', 7201, 'NULL', 13, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (173, 'Holešov', 7202, 'NULL', 13, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (174, 'Kroměříž', 7203, 'NULL', 13, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (175, 'Luhačovice', 7204, 'NULL', 13, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (176, 'Otrokovice', 7205, 'NULL', 13, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (177, 'Rožnov pod Radhoštěm', 7206, 'NULL', 13, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (178, 'Uherské Hradiště', 7207, 'NULL', 13, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (179, 'Uherský Brod', 7208, 'NULL', 13, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (180, 'Valašské Klobouky', 7209, 'NULL', 13, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (181, 'Valašské Meziříčí', 7210, 'NULL', 13, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (182, 'Vizovice', 7211, 'NULL', 13, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (183, 'Vsetín', 7212, 'NULL', 13, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (184, 'Zlín', 7213, 'NULL', 13, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (185, 'Bílovec', 8101, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (186, 'Bohumín', 8102, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (187, 'Bruntál', 8103, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (188, 'Český Těšín', 8104, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (189, 'Frenštát pod Radhoštěm', 8105, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (190, 'Frýdek-Místek', 8106, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (191, 'Frýdlant nad Ostravicí', 8107, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (192, 'Havířov', 8108, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (193, 'Hlučín', 8109, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (194, 'Jablunkov', 8110, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (195, 'Karviná', 8111, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (196, 'Kopřivnice', 8112, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (197, 'Kravaře', 8113, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (198, 'Krnov', 8114, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (199, 'Nový Jičín', 8115, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (200, 'Odry', 8116, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (201, 'Opava', 8117, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (202, 'Orlová', 8118, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (203, 'Ostrava', 8119, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (204, 'Rýmařov', 8120, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (205, 'Třinec', 8121, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (206, 'Vítkov', 8122, 'NULL', 14, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (1, 'Praha', 1000, 'NULL', 1, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (2, 'Benešov', 2101, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (3, 'Beroun', 2102, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (4, 'Brandýs nad Labem-Stará Boleslav', 2103, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (5, 'Čáslav', 2104, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (6, 'Černošice', 2105, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (7, 'Český Brod', 2106, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (8, 'Dobříš', 2107, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (9, 'Hořovice', 2108, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (10, 'Kladno', 2109, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (11, 'Kolín', 2110, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (12, 'Kralupy nad Vltavou', 2111, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (13, 'Kutná Hora', 2112, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (14, 'Lysá nad Labem', 2113, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (15, 'Mělník', 2114, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (16, 'Mladá Boleslav', 2115, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (17, 'Mnichovo Hradiště', 2116, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (18, 'Neratovice', 2117, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (19, 'Nymburk', 2118, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (20, 'Poděbrady', 2119, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (21, 'Příbram', 2120, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (22, 'Rakovník', 2121, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (23, 'Říčany', 2122, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (24, 'Sedlčany', 2123, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (25, 'Slaný', 2124, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (26, 'Vlašim', 2125, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (27, 'Votice', 2126, 'NULL', 2, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (28, 'Blatná', 3101, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (29, 'České Budějovice', 3102, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (30, 'Český Krumlov', 3103, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (31, 'Dačice', 3104, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (32, 'Jindřichův Hradec', 3105, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (33, 'Kaplice', 3106, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (34, 'Milevsko', 3107, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (35, 'Písek', 3108, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (36, 'Prachatice', 3109, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (37, 'Soběslav', 3110, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (38, 'Strakonice', 3111, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (39, 'Tábor', 3112, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (40, 'Trhové Sviny', 3113, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (41, 'Třeboň', 3114, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (42, 'Týn nad Vltavou', 3115, 'NULL', 3, 1);
INSERT INTO public.nuts4 (id, name, code_index, code, region_id, state_id) VALUES (43, 'Vimperk', 3116, 'NULL', 3, 1);